name: Python

on:
  schedule:
    -  cron: '0/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install requests_html
        run: pip install requests_html
      - name: Run Web Scrapper
        run: python web_scrap_fx.py
